default: &default
  adapter: postgresql
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db

development:
  <<: *default
  database: development_postresql

test:
  <<: *default
  database: test_postresql

production:
  <<: *default
  database: production_postresql
